# .scrutinizer.yml
checks:
        javascript:
        no_loop_var_assign: true
        no_else_return: true
        eqeqeq: true
build:
        nodes:
                analysis:
                        environment:
                                node:
                                        version: 8.0.0
